-- Optional Snowflake DDL. The Python loader can auto-create tables, but explicit DDL is useful for review.

CREATE OR REPLACE TABLE INDEX_FILES (
    INDEX_FILE_ID NUMBER,
    FILE_NAME STRING,
    LOCAL_PATH STRING,
    REPORTING_ENTITY_NAME STRING,
    REPORTING_ENTITY_TYPE STRING,
    LAST_UPDATED_ON STRING,
    VERSION STRING,
    PARSED_AT STRING
);

CREATE OR REPLACE TABLE REPORTING_ENTITIES (
    INDEX_FILE_ID NUMBER,
    REPORTING_ENTITY_NAME STRING,
    REPORTING_ENTITY_TYPE STRING,
    LAST_UPDATED_ON STRING,
    VERSION STRING
);

CREATE OR REPLACE TABLE PLANS (
    PLAN_KEY STRING,
    INDEX_FILE_ID NUMBER,
    PLAN_NAME STRING,
    PLAN_ID STRING,
    PLAN_ID_TYPE STRING,
    PLAN_MARKET_TYPE STRING
);

CREATE OR REPLACE TABLE REFERENCED_FILES (
    REFERENCED_FILE_KEY STRING,
    PLAN_KEY STRING,
    INDEX_FILE_ID NUMBER,
    FILE_TYPE STRING,
    DESCRIPTION STRING,
    LOCATION_URL STRING
);
