-- Analytical queries for exploring the parsed UHC data in Snowflake.
-- These match the insights generated by 04_generate_insights.py.

-- 1. Which entities have the most index files?
SELECT REPORTING_ENTITY_NAME,
       REPORTING_ENTITY_TYPE,
       COUNT(*) AS INDEX_FILE_COUNT
FROM INDEX_FILES
GROUP BY 1, 2
ORDER BY INDEX_FILE_COUNT DESC;

-- 2. How many plans does each index file contain?
SELECT INDEX_FILE_ID,
       COUNT(*) AS PLAN_COUNT
FROM PLANS
GROUP BY 1
ORDER BY PLAN_COUNT DESC;

-- 3. What types of plan IDs are used?
SELECT PLAN_ID_TYPE,
       COUNT(*) AS PLAN_COUNT
FROM PLANS
GROUP BY 1
ORDER BY PLAN_COUNT DESC;

-- 4. In-network vs allowed-amount file split
SELECT FILE_TYPE,
       COUNT(*) AS FILE_COUNT
FROM REFERENCED_FILES
GROUP BY 1
ORDER BY FILE_COUNT DESC;

-- 5. Which rate file URLs are referenced by the most plans?
--    (Shows data centralization: same rate file shared across many employers)
SELECT LOCATION_URL,
       COUNT(*)                      AS REFERENCE_COUNT,
       COUNT(DISTINCT INDEX_FILE_ID) AS DISTINCT_INDEX_FILES
FROM REFERENCED_FILES
GROUP BY 1
ORDER BY REFERENCE_COUNT DESC
LIMIT 20;
