-- Example insight queries for Snowflake

-- Downloaded / parsed entities
SELECT REPORTING_ENTITY_NAME, REPORTING_ENTITY_TYPE, COUNT(*) AS INDEX_FILE_COUNT
FROM INDEX_FILES
GROUP BY 1, 2
ORDER BY INDEX_FILE_COUNT DESC;

-- Plans per index file
SELECT INDEX_FILE_ID, COUNT(*) AS PLAN_COUNT
FROM PLANS
GROUP BY 1
ORDER BY PLAN_COUNT DESC;

-- Plan ID type distribution
SELECT PLAN_ID_TYPE, COUNT(*) AS PLAN_COUNT
FROM PLANS
GROUP BY 1
ORDER BY PLAN_COUNT DESC;

-- Referenced file type distribution
SELECT FILE_TYPE, COUNT(*) AS REFERENCED_FILE_COUNT
FROM REFERENCED_FILES
GROUP BY 1
ORDER BY REFERENCED_FILE_COUNT DESC;

-- Most reused referenced URLs
SELECT LOCATION_URL,
       COUNT(*) AS REFERENCE_COUNT,
       COUNT(DISTINCT INDEX_FILE_ID) AS DISTINCT_INDEX_FILES
FROM REFERENCED_FILES
GROUP BY 1
ORDER BY REFERENCE_COUNT DESC
LIMIT 20;
